### PR TITLE
Devel

### PR DESCRIPTION
**Pull request by matteodefelice**
I tested this code reducing the execution time of about 3 times using 4
cores on my macbook.

### CODE REVIEW

**Comment by jbedia** [comment]
I have included your modifications to interpData. I do not accept the pull request to avoid conflicts. Your changes are in devel now. Thanks Matteo.

**Comment by matteodefelice** [comment]
I suggest including ``pbapply`` and a message saying that, in case of NAs/NANs, the interpolation would be slower.

**Comment by jbedia** [comment]
Note that anyNA was introduced after R3.0.0, so requires changing the Depends in DESCRIPTION. ¿Can you confirm the release version of anyNA?. I agree it is a good point to improve efficiency.

**Comment by jbedia** [comment]
pbApply introduces new package dependencies... ¿Is it really needed?

**Comment by matteodefelice** [comment]
well, I love progress bars but I think that in this case the decision is up to you, I agree that is not really needed.

**Comment by jbedia** [comment]
Matteo, I have updated interpData with all proposed changes but the progress bar... Do you think I can now close this thread?
cheers

**Comment by matteodefelice** [comment]
Yes, great work, thanks!

**Comment by jbedia** [comment]
Excellent Matteo, grazie

**Pull request closed without merging**
